export const careerLibrary = {
  "Data Analyst": { domainType: "Tech", shortDescription: "Turn data into decisions with dashboards and SQL.", insight: "Best for structured thinkers who want stable analytics-led growth.", growth: 74, risk: 32, lifestyle: 79, salaryBase: 12, salaryTop: 22, competition: "High", timeToBreakIn: "6-9 months", effort: "Consistent and structured practice", hours: "42 hrs/week", stress: "Moderate", workMode: "Hybrid / Remote-friendly", requiredSkills: ["SQL", "Excel", "Python", "Visualization", "Business storytelling"], strongSignals: ["Structured problem solving", "Communication", "Curiosity"], matchWeights: { Tech: 12, analytical: 15, leadership: 2, creative: 1, beginner: 8, moderate: 10, advanced: 5 } },
  "Data Scientist": { domainType: "Tech", shortDescription: "Build predictive insight with modeling and experimentation.", insight: "High-value path for users who enjoy statistics and deep analysis.", growth: 82, risk: 48, lifestyle: 68, salaryBase: 18, salaryTop: 30, competition: "High", timeToBreakIn: "10-14 months", effort: "Strong mathematics and project depth required", hours: "46 hrs/week", stress: "Moderate to High", workMode: "Hybrid / Remote-friendly", requiredSkills: ["Python", "Statistics", "Machine learning", "Data storytelling", "Experimentation"], strongSignals: ["Analytical depth", "Curiosity", "Pattern recognition"], matchWeights: { Tech: 14, analytical: 18, leadership: 1, creative: 1, beginner: 2, moderate: 10, advanced: 14 } },
  "Machine Learning Engineer": { domainType: "Tech", shortDescription: "Productionize models, pipelines, and intelligent systems at scale.", insight: "Strong upside for users who want deep technical leverage.", growth: 88, risk: 58, lifestyle: 59, salaryBase: 22, salaryTop: 36, competition: "Rising Fast", timeToBreakIn: "12-18 months", effort: "Deep technical practice and engineering rigor", hours: "50 hrs/week", stress: "High", workMode: "Remote-friendly", requiredSkills: ["Python", "Model deployment", "MLOps", "Data pipelines", "System design"], strongSignals: ["Technical depth", "Learning speed", "Experimentation"], matchWeights: { Tech: 16, analytical: 14, leadership: 0, creative: 0, beginner: 0, moderate: 8, advanced: 18 } },
  "AI Engineer": { domainType: "Tech", shortDescription: "Build AI-native products using LLM tooling and system design.", insight: "Highest upside path for users ready to combine AI fluency and engineering.", growth: 91, risk: 62, lifestyle: 58, salaryBase: 24, salaryTop: 40, competition: "Very High", timeToBreakIn: "12-18 months", effort: "Continuous upskilling and shipping", hours: "50 hrs/week", stress: "High", workMode: "Remote-friendly", requiredSkills: ["Python", "LLM tooling", "Prompt systems", "Model evaluation", "System design"], strongSignals: ["Technical depth", "Adaptability", "Bias for action"], matchWeights: { Tech: 18, analytical: 12, leadership: 0, creative: 1, beginner: 0, moderate: 7, advanced: 20 } },
  "Software Developer": { domainType: "Tech", shortDescription: "Build production software across backend systems and product features.", insight: "Reliable growth path for builders who enjoy solving engineering problems.", growth: 80, risk: 44, lifestyle: 67, salaryBase: 16, salaryTop: 28, competition: "High", timeToBreakIn: "8-12 months", effort: "Strong practice and portfolio discipline", hours: "46 hrs/week", stress: "Moderate", workMode: "Hybrid / Remote-friendly", requiredSkills: ["JavaScript", "APIs", "Data structures", "Git", "Debugging"], strongSignals: ["Problem solving", "Resilience", "Execution"], matchWeights: { Tech: 15, analytical: 10, leadership: 2, creative: 1, beginner: 8, moderate: 12, advanced: 10 } },
  "Web Developer": { domainType: "Tech", shortDescription: "Create modern web experiences with frontend systems and full-stack delivery.", insight: "Accessible high-demand path with strong portfolio visibility.", growth: 73, risk: 36, lifestyle: 75, salaryBase: 12, salaryTop: 20, competition: "High", timeToBreakIn: "5-8 months", effort: "Consistent shipping and interface practice", hours: "42 hrs/week", stress: "Moderate", workMode: "Remote-friendly", requiredSkills: ["HTML/CSS", "JavaScript", "React", "Responsive design", "APIs"], strongSignals: ["Visual thinking", "Execution", "Iteration"], matchWeights: { Tech: 12, analytical: 6, leadership: 1, creative: 8, beginner: 12, moderate: 10, advanced: 5 } },
  "Cybersecurity Analyst": { domainType: "Tech", shortDescription: "Protect systems, detect threats, and strengthen resilience.", insight: "Great for methodical thinkers who want mission-critical work.", growth: 79, risk: 43, lifestyle: 63, salaryBase: 14, salaryTop: 24, competition: "Medium", timeToBreakIn: "8-12 months", effort: "Hands-on labs and certification work", hours: "45 hrs/week", stress: "Moderate to High", workMode: "Hybrid / Office-heavy", requiredSkills: ["Networking", "Threat analysis", "Security tools", "Incident response", "Compliance basics"], strongSignals: ["Discipline", "Attention to detail", "Calm under pressure"], matchWeights: { Tech: 14, analytical: 13, leadership: 1, creative: 0, beginner: 6, moderate: 12, advanced: 9 } },
  "Cloud Engineer": { domainType: "Tech", shortDescription: "Design scalable infrastructure and automate modern deployment environments.", insight: "Strong option for users who like systems thinking and platform leverage.", growth: 84, risk: 47, lifestyle: 61, salaryBase: 18, salaryTop: 30, competition: "Medium", timeToBreakIn: "9-14 months", effort: "Technical consistency and platform depth", hours: "47 hrs/week", stress: "Moderate to High", workMode: "Hybrid / Remote-friendly", requiredSkills: ["Cloud platforms", "Linux", "Containers", "IaC", "Monitoring"], strongSignals: ["Systems thinking", "Reliability mindset", "Automation focus"], matchWeights: { Tech: 16, analytical: 12, leadership: 1, creative: 0, beginner: 3, moderate: 10, advanced: 14 } },
  "Business Analyst": { domainType: "Business", shortDescription: "Bridge business goals and execution through analysis and process clarity.", insight: "Strong fit for users who want strategy plus structure.", growth: 71, risk: 29, lifestyle: 77, salaryBase: 11, salaryTop: 19, competition: "Medium", timeToBreakIn: "5-8 months", effort: "Communication and analytical clarity", hours: "41 hrs/week", stress: "Moderate", workMode: "Hybrid", requiredSkills: ["Requirements gathering", "Excel", "Process mapping", "Communication", "Documentation"], strongSignals: ["Stakeholder empathy", "Structure", "Business thinking"], matchWeights: { Tech: 3, analytical: 12, leadership: 6, creative: 1, beginner: 10, moderate: 11, advanced: 5 } },
  "Product Manager": { domainType: "Business", shortDescription: "Drive product direction through strategy and user-centered prioritization.", insight: "Ideal for users who combine communication, ownership, and business context.", growth: 83, risk: 55, lifestyle: 64, salaryBase: 18, salaryTop: 32, competition: "Very High", timeToBreakIn: "9-15 months", effort: "High ownership and ambiguity tolerance", hours: "48 hrs/week", stress: "High", workMode: "Hybrid / Office-heavy", requiredSkills: ["Roadmapping", "Stakeholder management", "Analytics", "User research", "Prioritization"], strongSignals: ["Leadership", "Decision-making", "Narrative building"], matchWeights: { Tech: 4, analytical: 8, leadership: 18, creative: 4, beginner: 1, moderate: 9, advanced: 16 } },
  "Operations Analyst": { domainType: "Business", shortDescription: "Improve systems, workflows, and performance across teams.", insight: "Good for users who like process optimization and operational impact.", growth: 69, risk: 27, lifestyle: 80, salaryBase: 10, salaryTop: 18, competition: "Medium", timeToBreakIn: "4-7 months", effort: "Structured execution and consistency", hours: "40 hrs/week", stress: "Low to Moderate", workMode: "Hybrid", requiredSkills: ["Process mapping", "Excel", "Operations reporting", "Coordination", "Problem solving"], strongSignals: ["Reliability", "Structure", "Execution"], matchWeights: { Tech: 1, analytical: 11, leadership: 5, creative: 0, beginner: 12, moderate: 10, advanced: 2 } },
  "Marketing Analyst": { domainType: "Business", shortDescription: "Use campaign data and customer insight to improve acquisition and growth.", insight: "High fit for users who like analytics with direct business visibility.", growth: 70, risk: 35, lifestyle: 74, salaryBase: 11, salaryTop: 20, competition: "Medium to High", timeToBreakIn: "5-8 months", effort: "Data fluency and experimentation", hours: "43 hrs/week", stress: "Moderate", workMode: "Hybrid / Remote-friendly", requiredSkills: ["Campaign analytics", "SQL basics", "Attribution", "Experimentation", "Storytelling"], strongSignals: ["Analytical thinking", "Commercial instinct", "Communication"], matchWeights: { Tech: 2, analytical: 13, leadership: 4, creative: 5, beginner: 8, moderate: 11, advanced: 6 } },
  "UI/UX Designer": { domainType: "Creative", shortDescription: "Design intuitive digital experiences through research and interface craft.", insight: "Best for users who blend empathy, visual taste, and product thinking.", growth: 76, risk: 39, lifestyle: 76, salaryBase: 12, salaryTop: 22, competition: "High", timeToBreakIn: "7-10 months", effort: "Portfolio quality and user-centered thinking", hours: "43 hrs/week", stress: "Moderate", workMode: "Hybrid / Remote-friendly", requiredSkills: ["Wireframing", "Visual systems", "Research", "Interaction design", "Portfolio building"], strongSignals: ["Empathy", "Design taste", "Storytelling"], matchWeights: { Tech: 3, analytical: 5, leadership: 2, creative: 18, beginner: 9, moderate: 11, advanced: 5 } },
  "Content Strategist": { domainType: "Creative", shortDescription: "Shape messaging and content systems across products and brands.", insight: "Great for users who enjoy structure, communication, and audience insight.", growth: 67, risk: 31, lifestyle: 81, salaryBase: 9, salaryTop: 17, competition: "Medium", timeToBreakIn: "4-7 months", effort: "Consistent writing and strategic clarity", hours: "39 hrs/week", stress: "Low to Moderate", workMode: "Remote-friendly", requiredSkills: ["Content planning", "Messaging", "SEO basics", "Research", "Editorial systems"], strongSignals: ["Writing clarity", "Audience empathy", "Narrative structure"], matchWeights: { Tech: 0, analytical: 4, leadership: 3, creative: 16, beginner: 12, moderate: 9, advanced: 3 } },
  "Digital Marketer": { domainType: "Creative", shortDescription: "Grow audiences through campaigns, analytics, and channel strategy.", insight: "A fast-moving path for users who want business visibility with creative experimentation.", growth: 72, risk: 41, lifestyle: 70, salaryBase: 10, salaryTop: 19, competition: "High", timeToBreakIn: "4-8 months", effort: "Experimentation and strong execution cadence", hours: "42 hrs/week", stress: "Moderate", workMode: "Hybrid / Remote-friendly", requiredSkills: ["Campaign execution", "Ads platforms", "Analytics", "Copywriting", "Funnel thinking"], strongSignals: ["Creativity", "Commercial instinct", "Speed"], matchWeights: { Tech: 1, analytical: 6, leadership: 3, creative: 14, beginner: 10, moderate: 10, advanced: 6 } },
};

export const domainOptions = ["All", "Tech", "Business", "Creative"];
export const difficultyOptions = ["Beginner", "Moderate", "Advanced"];
export const skillOptions = [
  { value: 0, label: "Current" },
  { value: 1, label: "Improving" },
  { value: 2, label: "Aggressive" },
];
export const riskOptions = ["Low", "Medium", "High"];
